#
# version.cmake : version du projet
#

set (TK_UTIL_MAJOR_VERSION "5")
set (TK_UTIL_MINOR_VERSION "13")
set (TK_UTIL_RELEASE_VERSION "2")
set (TK_UTIL_VERSION ${TK_UTIL_MAJOR_VERSION}.${TK_UTIL_MINOR_VERSION}.${TK_UTIL_RELEASE_VERSION})

set (TK_UTIL_SCRIPTING_MAJOR_VERSION ${TK_UTIL_MAJOR_VERSION})
set (TK_UTIL_SCRIPTING_MINOR_VERSION ${TK_UTIL_MINOR_VERSION})
set (TK_UTIL_SCRIPTING_RELEASE_VERSION ${TK_UTIL_RELEASE_VERSION})
set (TK_UTIL_SCRIPTING_VERSION ${TK_UTIL_VERSION})

